<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Finora.Cms.Application\Finora.Cms.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Finora.BuildingBlocks.Infrastructure\Finora.BuildingBlocks.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
  </PropertyGroup>

</Project>
