<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\Finora.BuildingBlocks.Domain\Finora.BuildingBlocks.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Erp\Finora.Erp.Domain\Finora.Erp.Domain.csproj" />
  </ItemGroup>

</Project>