<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Finora.ServiceDefaults\Finora.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Modules\Identity\Finora.Identity.Infrastructure\Finora.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Cms\Finora.Cms.Infrastructure\Finora.Cms.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Erp\Finora.Erp.Infrastructure\Finora.Erp.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <PropertyGroup>
  </PropertyGroup>

</Project>
